app/Models/Publisher.cs
using System.ComponentModel.DataAnnotations;

namespace app.Models
{
    public class Publisher
    {
        public Publisher()
        {

        }

        [Key]
        public int publisher_id { get; set; }

        public string? publisher_name { get; set; }

        public ICollection<Book>? Books { get; set; }
    }
}

app/Controllers/CategoryController.cs
using app.Models;
using library.Data;
using library.Service;
using library.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Net;

namespace library.Controllers
{
    public class CategoryController : Controller
    {

        private readonly CategoryService _categoryService;

        public CategoryController(CategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            IEnumerable<app.Models.Category>? objCategoryList = _categoryService.GetCategories();
            return View(objCategoryList);
        }

        // GET: Products/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var book = _categoryService.GetCategories().FirstOrDefault(m => m.category_id == id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }



        //GET
        public IActionResult Create()
        {
            return View();
        }



        //POST
        [HttpPost]
        [ValidateAntiForgeryToken] //avoid xss
        public IActionResult Create(app.Models.Category obj)
        {
            if (ModelState.IsValid)
            {
                _categoryService.AddCategory(obj);
                _categoryService.Save();
                return RedirectToAction("Index");
            }

            return View(obj);

        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            var data = _categoryService.GetCategories().Where(x => x.category_id == id).FirstOrDefault();
            return View(data);
        }
        [HttpPost]
        public IActionResult Edit(app.Models.Category Model)
        {
            var data = _categoryService.GetCategories().Where(x => x.category_id == Model.category_id).FirstOrDefault();
            if (data != null)
            {
                _categoryService.UpdateCategory(data);
                _categoryService.Save();
            }

            return RedirectToAction("index");
        }


        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //get author by id
            var categoryFromDb = _categoryService.GetCategories().FirstOrDefault(m => m.category_id == id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }


        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Category? category = _categoryService.GetCategoriesByCondition(b => b.category_id == id).FirstOrDefault();

            if (category == null)
            {
                return NotFound();
            }

            _categoryService.DeleteCategory(category);
            _categoryService.Save();
            return RedirectToAction("Index");
        }

    }
}

app/Controllers/PublisherController.cs
using app.Models;
using library.Data;
using library.Service;
using library.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Net;

namespace library.Controllers
{
    public class PublisherController : Controller
    {

        private readonly PublisherService _publisherService;

        public PublisherController(PublisherService publisherService)
        {
            _publisherService = publisherService;
        }

        public IActionResult Index()
        {
            IEnumerable<app.Models.Publisher>? objPublisherList = _publisherService.GetPublishers();
            return View(objPublisherList);
        }

        // GET: Products/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var publisher = _publisherService.GetPublishers().FirstOrDefault(m => m.publisher_id == id);
            if (publisher == null)
            {
                return NotFound();
            }
            return View(publisher);
        }



        //GET
        public IActionResult Create()
        {
            return View();
        }



        //POST
        [HttpPost]
        [ValidateAntiForgeryToken] //avoid xss
        public IActionResult Create(app.Models.Publisher obj)
        {
            if (ModelState.IsValid)
            {
                _publisherService.AddPublisher(obj);
                _publisherService.Save();
                return RedirectToAction("Index");
            }

            return View(obj);

        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            var data = _publisherService.GetPublishers().Where(x => x.publisher_id == id).FirstOrDefault();
            return View(data);
        }
        [HttpPost]
        public IActionResult Edit(app.Models.Publisher Model)
        {
            var data = _publisherService.GetPublishers().Where(x => x.publisher_id == Model.publisher_id).FirstOrDefault();
            if (data != null)
            {
                _publisherService.UpdatePublisher(data);
                _publisherService.Save();
            }

            return RedirectToAction("index");
        }


        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //get author by id
            var publisherFromDb = _publisherService.GetPublishers().FirstOrDefault(m => m.publisher_id == id);

            if (publisherFromDb == null)
            {
                return NotFound();
            }

            return View(publisherFromDb);
        }


        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Publisher? publisher = _publisherService.GetPublishersByCondition(b => b.publisher_id == id).FirstOrDefault();

            if (publisher == null)
            {
                return NotFound();
            }

            _publisherService.DeletePublisher(publisher);
            _publisherService.Save();
            return RedirectToAction("Index");
        }

    }
}

app/Views/Publisher/Create.cshtml
@model Category

<form method="post" asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Category</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
             <!--bining everything with category model-->
             <label asp-for="category_name">Name</label>
             <input asp-for="category_name" />
             <span asp-validation-for="category_name" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width: 150px">Create</button>
        <a asp-controller="Category" asp-action="Index" class="btn btn-secondary" style="width: 150px">
            Back to list
        </a>
    </div>
</form>


@*do validations on client side instead of doing them on server side*@
@section Scripts {
    @{
         <partial name="_ValidationScriptsPartial" />
    }
}

app/Views/Publisher/Delete.cshtml
@model Category

<form method="post" asp-action="DeletePOST">
	<input asp-for="category_id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-danger">Delete Category</h2>
			<hr />
		</div>
		<div asp-validation-summary="All"></div>
		<div class="mb-3">
			<label asp-for="category_name"></label>
			<input asp-for="category_name" class="form-control" disabled/>
			<span asp-validation-for="category_name" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="Category" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

app/Views/Publisher/Details.cshtml
@model Publisher

<h2>Publisher details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.publisher_name)
        </dt>

        <dd>
            @Html.DisplayFor(model =>  model.publisher_name)
        </dd>
    </dl>
</div>
<p>
    <div class="w-75 btn-group" role="group">
       @Html.ActionLink("Back to publishers", "Index")
    </div>
</p>

app/Views/Publisher/Edit.cshtml
@model Category

<form method="post" asp-action="Edit">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Edit Category</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="category_name"></label>
			<input asp-for="category_name" class="form-control" />
			<span asp-validation-for="category_name" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
		<a asp-controller="Category" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

app/Views/Publisher/Index.cshtml
@model IEnumerable<Publisher>
@{
    ViewData["Title"] = "Index";
}


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Publishers List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Publisher" asp-action="Create" class="btn btn-success">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Publisher
            </a>
        </div>
        <br />
        <br />
    </div>
</div>

<table class="table table-bordered table-striped" style="width: 100%">
    <thead>
       <tr>
           <th>
               Publisher Id
           </th>
           <th>
               Publisher Name
           </th>
           <th>
               Actions
           </th>
       </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td>
                    @obj.publisher_id
                </td>
                 <td>
                    @obj.publisher_name
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Publisher" asp-action="Details" asp-route-id="@obj.publisher_id" class="btn btn-secodnary mx-2">
                            <i class="bi bi-eye-fill"></i>Details
                        </a>
                        <a asp-controller="Publisher" asp-action="Edit" asp-route-id="@obj.publisher_id" class="btn btn-secodnary mx-2">
                            <i class="bi bi-pen-fill"></i> Edit
                        </a>
                        <a asp-controller="Publisher" asp-action="Delete" asp-route-id="@obj.publisher_name" class="btn btn-secodnary mx-2">
                            <i class="bi bi-trash-fill"></i> Delete
                        </a>
                    </div>

                </td>
            </tr>
        }
    </tbody>
</table>