app/Controllers/AuthorController.cs
using app.Models;
using library.Data;
using library.Service;
using library.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Net;

namespace library.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AuthorController : Controller
    {

        private readonly AuthorService _authorService;

        public AuthorController(AuthorService authorService)
        {
            _authorService = authorService;
        }

        public IActionResult Index()
        {
            IEnumerable<app.Models.Author>? objAuthorList = _authorService.GetAuthors();
            return View(objAuthorList);
        }

        // GET: Products/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var author = _authorService.GetAuthors().FirstOrDefault(m => m.author_id == id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }



        //GET
        public IActionResult Create()
        {
            return View();
        }



        //POST
        [HttpPost]
        [ValidateAntiForgeryToken] //avoid xss
        public IActionResult Create(app.Models.Author obj)
        {
            if (ModelState.IsValid)
            {
                _authorService.AddAuthor(obj);
                _authorService.Save();
                return RedirectToAction("Index");
            }

            return View(obj);

        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            var data = _authorService.GetAuthors().Where(x => x.author_id == id).FirstOrDefault();
            return View(data);
        }
        [HttpPost]
        public IActionResult Edit(app.Models.Author Model)
        {
            var data = _authorService.GetAuthors().Where(x => x.author_id == Model.author_id).FirstOrDefault();
            if (data != null)
            {
                _authorService.UpdateAuthor(data);
                _authorService.Save();
            }

            return RedirectToAction("index");
        }


        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //get author by id
            var authorFromDb = _authorService.GetAuthors().FirstOrDefault(m => m.author_id == id);

            if (authorFromDb == null)
            {
                return NotFound();
            }

            return View(authorFromDb);
        }


        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Author? author = _authorService.GetAuthorsByCondition(b => b.author_id == id).FirstOrDefault();

            if (author == null)
            {
                return NotFound();
            }

            _authorService.DeleteAuthor(author);
            _authorService.Save();
            return RedirectToAction("Index");
        }

    }
}

app/Controllers/BookController.cs
using app.Models;
using library.Data;
using library.Service;
using library.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Net;

namespace library.Controllers
{
    public class BookController : Controller
    {
        //private readonly ApplicationDbContext _db;

        private readonly BookService _bookService;

        public BookController(BookService bookService)
        {
            //_db = db;
            _bookService = bookService;
        }

        public IActionResult Index()
        {
            IEnumerable<app.Models.Book>? objBookList = _bookService.GetBooks();
            return View(objBookList);
        }

        // GET: Products/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var book = _bookService.GetBooks().FirstOrDefault(m => m.book_id == id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }



        //GET
        public IActionResult Create()
        {
            return View();
        }



        //POST
        [HttpPost]
        [ValidateAntiForgeryToken] //avoid xss
        public IActionResult Create(app.Models.Book obj)
        {
            if (ModelState.IsValid)
            {
                _bookService.AddBook(obj);
                _bookService.Save();
                return RedirectToAction("Index");
            }

            return View(obj);

        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            var data = _bookService.GetBooks().Where(x => x.book_id == id).FirstOrDefault();
            return View(data);
        }
        [HttpPost]
        public IActionResult Edit(app.Models.Book Model)
        {
            var data = _bookService.GetBooks().Where(x => x.book_id == Model.book_id).FirstOrDefault();
            if (data != null)
            {
                _bookService.UpdateBook(data);
                _bookService.Save();
            }

            return RedirectToAction("index");
        }


        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //get author by id
            var bookFromDb = _bookService.GetBooks().FirstOrDefault(m => m.book_id == id);

            if (bookFromDb == null)
            {
                return NotFound();
            }

            return View(bookFromDb);
        }


        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Book? book = _bookService.GetBooksByCondition(b => b.book_id == id).FirstOrDefault();

            if (book == null)
            {
                return NotFound();
            }

            _bookService.DeleteBook(book);
            _bookService.Save();
            return RedirectToAction("Index");
        }

    }
}

app/Controllers/MemberController.cs
using app.Models;
using library.Data;
using library.Service;
using library.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Net;

namespace library.Controllers
{
    public class MemberController : Controller
    {

        private readonly MemberService _memberService;

        public MemberController(MemberService memberService)
        {
            _memberService = memberService;
        }

        public IActionResult Index()
        {
            IEnumerable<app.Models.Member>? objMemberList = _memberService.GetMembers();
            return View(objMemberList);
        }

        // GET: Products/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var member = _memberService.GetMembers().FirstOrDefault(m => m.member_id == id);
            if (member == null)
            {
                return NotFound();
            }
            return View(member);
        }



        //GET
        public IActionResult Create()
        {
            return View();
        }



        //POST
        [HttpPost]
        [ValidateAntiForgeryToken] //avoid xss
        public IActionResult Create(app.Models.Member obj)
        {
            if (ModelState.IsValid)
            {
                _memberService.AddMember(obj);
                _memberService.Save();
                return RedirectToAction("Index");
            }

            return View(obj);

        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            var data = _memberService.GetMembers().Where(x => x.member_id == id).FirstOrDefault();
            return View(data);
        }
        [HttpPost]
        public IActionResult Edit(app.Models.Member Model)
        {
            var data = _memberService.GetMembers().Where(x => x.member_id == Model.member_id).FirstOrDefault();
            if (data != null)
            {
                _memberService.UpdateMember(data);
                _memberService.Save();
            }

            return RedirectToAction("index");
        }


        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //get author by id
            var memberFromDb = _memberService.GetMembers().FirstOrDefault(m => m.member_id == id);

            if (memberFromDb == null)
            {
                return NotFound();
            }

            return View(memberFromDb);
        }


        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Member? member = _memberService.GetMembersByCondition(b => b.member_id == id).FirstOrDefault();

            if (member == null)
            {
                return NotFound();
            }

            _memberService.DeleteMember(member);
            _memberService.Save();
            return RedirectToAction("Index");
        }

    }
}

app/Controllers/ShopController.cs
using library.Service;
using Microsoft.AspNetCore.Mvc;

namespace library.Controllers
{
    public class ShopController : Controller
    {
        private readonly BookService _bookService;

        public ShopController(BookService bookService)
        {
            _bookService = bookService;
        }

        public IActionResult Index()
        {
            IEnumerable<app.Models.Book>? objBookList = _bookService.GetBooks();
            return View(objBookList);
        }
    }
}

app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - app</title>
    <link rel="stylesheet" href="~/css/bootswatchtheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/app.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="/#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02"                aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor02">
              <ul class="navbar-nav me-auto">
                <li class="nav-item">
                  <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                        @if (User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Shop" asp-action="Index">Library</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Author" asp-action="Index">Authors</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Publisher" asp-action="Index">Publishers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Member" asp-action="Index">Members</a>
                            </li>
                        }
                        

              </ul>
              <partial name="_LoginPartial" />
              <form class="d-flex" data-dashlane-rid="b599136a6ed9f990" data-form-type="">
                <input class="form-control me-sm-2" type="text" placeholder="Search" data-dashlane-rid="510b4258c7af69ab" data-form-type="">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit" data-dashlane-label="true" data-dashlane-rid="cba0ac87fcd437db" data-                  form-type="">Search</button>
              </form>
              
            </div>
          </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
 
        </main>
    </div>
    @RenderBody()
    @await Component.InvokeAsync("NToastNotify")
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>